"""audioforge-client: WebSocket client and message framing for the audioforge streaming speech server.

The server (``audioforge-serve``, https://github.com/maxmelichov/audioforge) runs a streaming ASR
with speech, turn and speaker heads on one 80 ms clock and emits ``frame`` / ``partial`` / ``turn_end_hint`` /
``turn_end`` / ``final`` events over a WebSocket (docs/PROTOCOL.md). This package has no model code and no torch
dependency: it is what a voice-agent framework plugin (Pipecat, LiveKit Agents, ...) needs to talk to it.
"""

from .protocol import (
    AGENT_END_MODES,
    DEFAULT_EOT_THRESHOLD,
    DEFAULT_SAMPLE_RATE,
    DEFAULT_URL,
    ENROLL_MODES,
    FINAL_SOURCES,
    FINAL_TEXTS,
    FRAME_MS,
    HYBRID_POLICIES,
    NUM_SPEAKERS,
    POLICIES,
    POLICY_EOT_THRESHOLD,
    TURN_PRESETS,
    Enrolled,
    Event,
    Final,
    FrameEvent,
    LanguageEvent,
    Partial,
    Ready,
    ServerError,
    Stats,
    TurnEnd,
    TurnHint,
    TurnHintCancel,
    Unknown,
    Voiceprint,
    config_message,
    control_message,
    cut_policy,
    final_source_of,
    parse_dict,
    parse_message,
    pcm16_duration_s,
    use_final,
)
from .session import AudioforgeClosedError, AudioforgeConnectionError, AudioforgeSession

__version__ = "0.2.0"

__all__ = [
    "AGENT_END_MODES",
    "DEFAULT_EOT_THRESHOLD",
    "DEFAULT_SAMPLE_RATE",
    "DEFAULT_URL",
    "ENROLL_MODES",
    "FINAL_SOURCES",
    "FINAL_TEXTS",
    "FRAME_MS",
    "HYBRID_POLICIES",
    "NUM_SPEAKERS",
    "POLICIES",
    "POLICY_EOT_THRESHOLD",
    "TURN_PRESETS",
    "AudioforgeClosedError",
    "AudioforgeConnectionError",
    "AudioforgeSession",
    "Enrolled",
    "Event",
    "Final",
    "FrameEvent",
    "LanguageEvent",
    "Partial",
    "Ready",
    "ServerError",
    "Stats",
    "TurnEnd",
    "TurnHint",
    "TurnHintCancel",
    "Unknown",
    "Voiceprint",
    "__version__",
    "config_message",
    "control_message",
    "cut_policy",
    "final_source_of",
    "parse_dict",
    "parse_message",
    "pcm16_duration_s",
    "use_final",
]
