"""Render the redesigned post images (DESIGN_NOTES.md) at 2x with the film's Playwright venv, run the checks, and
write half-size copies next to this file.

    /Volumes/afdev/venvs/video/bin/python demo/images/redesign/render.py [arch|results]
      -> $DEMO_OUT/images_redesign/{A1_flow,A2_stack,B1_grid,B2_list}{,_square}.png  (3840x2160 / 2160x2160)
      -> demo/images/redesign/*.png (1920x1080 / 1080x1080 half-size copies), checks.json

Checks, in CSS px (1x): every text >= 22 px; every text >= 64 px from the frame edge; contrast >= 7:1 against the
nearest painted ancestor background; no two text runs intersect; no clipped / overflowing text; every [data-key]
value equals the numbers_b.json "shown" string (the pages read demo/v5/shots/numbers_b.js, generated by export_b.py).
One Chromium, one page at a time.
"""
from __future__ import annotations

import json
import os
import shutil
import sys
from pathlib import Path

from PIL import Image

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[2]
OUT = Path(os.environ.get("DEMO_OUT", "/Volumes/ExternalSSD/nvidia-audio-models/demo_out")) / "images_redesign"
NB = json.loads((ROOT / "demo" / "v5" / "shots" / "numbers_b.json").read_text())

JOBS = {
    "arch": [("arch.html", "flow", "A1_flow"), ("arch.html", "stack", "A2_stack")],
    "results": [("results.html", "grid", "B1_grid"), ("results.html", "list", "B2_list")],
    "single": [("arch_single.html", "flow", "architecture_single"), ("results_single.html", "grid", "results_single")],
    "v3": [("arch_v3.html", "v3", "architecture_v3"), ("results_v3.html", "grid", "results_v3")],
    "v4": [("arch_v4.html", "v4", "architecture_v4")],
    "v5": [("arch_v5.html", "v5", "architecture_v5")],
    "v6": [("arch_v6.html", "v6", "architecture_v6")],
    "r4": [("results_v4.html", "grid", "results_v4")],
    "v7": [("arch_v7.html", "v7", "architecture_v7")],
    "r5": [("results_v5.html", "grid", "results_v5")],
    "r6": [("results_v6.html", "grid", "results_v6")],
    "r7": [("results_v7.html", "grid", "results_v7")],
    "v8": [("arch_v8.html", "v8", "architecture_v8")],
    "r8": [("results_v8.html", "grid", "results_v8")],
    "r9": [("results_v9.html", "grid", "results_v9")],
    "r10": [("results_v10.html", "grid", "results_v10")],
    "v9": [("arch_v9.html", "v9", "architecture_v9")],
}
FINAL = {"results_v9", "results_v10", "architecture_v9"}   # also copied to $DEMO_OUT/images (full size) and demo/images (half size)
# v8 content rules (the user's): standard metric names only, no home-made names, 115M model only
BANNED_V8 = ["dead air", "cut-in", "cut in", "cutin", "first words", "unanswered", "0.6b", "0.6 b", "parakeet", "talks over",
             "interruptions / call", "per call", "finds your voice", "hears speech"]
V8 = r"""() => {
  const st = document.getElementById("stage"), text = st.innerText.toLowerCase(), fails = [];
  const cards = [...st.querySelectorAll("[data-panel]")];
  cards.forEach(c => { const k = c.dataset.panel;
    const pl = c.querySelector("[data-plain]"); if (!pl || pl.textContent.trim().split(/\s+/).length < 6) fails.push(`card ${k}: no plain-English line`);
    if (!c.querySelector("[data-metric]")) fails.push(`card ${k}: no metric name`);
    if (!c.querySelector("[data-cue]")) fails.push(`card ${k}: no BETTER cue`);
    if (/\bF1\b/.test(c.innerText) && !/F1 (balances|:)/.test(pl ? pl.textContent : "")) fails.push(`card ${k}: F1 without its meaning in the plain line`); });
  return { text, fails, overflow: (window.BARCOUNT || {}).overflow || 0, ncards: cards.length };
}"""
NS = json.loads((HERE / "numbers_single.json").read_text()) if (HERE / "numbers_single.json").exists() else {}

# v9 (the user's mock-up): four cards, paired bars, a bracket with the relative change on every chart. Latency is not shown.
BANNED_V9 = BANNED_V8 + ["latency", " ms", "p50"]
V9 = r"""() => {
  const st = document.getElementById("stage"), fails = [];
  const cards = [...st.querySelectorAll("[data-panel]")];
  cards.forEach(c => { const k = c.dataset.panel;
    const pl = c.querySelector("[data-plain]"); if (!pl || pl.textContent.trim().split(/\s+/).length < 6) fails.push(`card ${k}: no plain-English line`);
    if (!c.querySelector(".fn")) fails.push(`card ${k}: no footnote`);
    const nm = c.querySelectorAll("[data-metric]").length, nd = c.querySelectorAll("[data-rel]").length, nb = c.querySelectorAll("[data-barval]").length;
    if (!nm || nd !== nm || nb !== 2 * nm) fails.push(`card ${k}: ${nm} charts, ${nd} changes, ${nb} bar values`);
    if (/\bF1\b/.test(c.innerText) && !/F1/.test(pl ? pl.textContent : "")) fails.push(`card ${k}: F1 without its meaning in the plain line`); });
  const tw = st.querySelector('[data-panel="twer"]');   // the 63 is our own STT with no speaker filter, not LiveKit / Pipecat
  if (tw && /livekit|pipecat/i.test(tw.innerText)) fails.push("tWER card names LiveKit / Pipecat: its grey bar is 'no speaker filter'");
  if (tw && !/no speaker filter/.test(tw.innerText)) fails.push("tWER card: grey bar not labelled 'no speaker filter'");
  const rels = [...st.querySelectorAll("[data-rel]")].map(d => ({ rel: d.dataset.rel, ours: d.dataset.ours, other: d.dataset.other, lower: d.dataset.lower === "1", arrow: d.textContent.trim()[0] }));
  return { text: st.innerText.toLowerCase(), fails, ncards: cards.length, rels, bars: window.BARS, charts: window.CHARTS };
}"""


# v10: turn head v5; the calls card shows end-of-turn latency again (a near-tie), so latency words are allowed
BANNED_V10 = BANNED_V8
V10_CARDS = {"asst": 2, "calls": 3, "twer": 1, "vad": 1}


def check_v10(c9, panels):
    fails = check_v9(c9, banned=BANNED_V10)
    for k, n in V10_CARDS.items():
        if panels.get(k) != n:
            fails.append(f"card {k}: {panels.get(k)} charts, want {n}")
    want = {"v10/asst/acc_rel", "v10/asst/ff_rel", "v10/calls/eot_rel", "v10/calls/fi_rel", "v10/calls/miss_rel", "v9/twer/rel", "v9/vad/rel"}
    got = {r["rel"] for r in c9["rels"]}
    if got != want:
        fails.append(f"changes {sorted(got ^ want)} differ from the v10 set")
    return fails


def check_v9(c9, banned=None):
    """v9 rules: each change = formula over the bar labels as printed (numbers_single "shown"; so it cannot be typed and a
    reader dividing the labels gets the printed %), arrow matches the
    direction, every bar's height matches its value on its axis."""
    fails = list(c9["fails"])
    if c9["ncards"] != 4:
        fails.append(f"{c9['ncards']} cards, want 4")
    for r in c9["rels"]:
        o, b = float(NS[r["ours"]]["shown"]), float(NS[r["other"]]["shown"])   # the change is computed from the printed bar labels
        want = 100 * (1 - o / b) if r["lower"] else 100 * (o / b - 1)
        got = NS[r["rel"]]
        if abs(got["value"] - want) > 1e-9 or want <= 0:
            fails.append(f"change {r['rel']}: file {got['value']} != formula {want}")
        if r["arrow"] != ("\u2193" if r["lower"] else "\u2191"):
            fails.append(f"change {r['rel']}: arrow {r['arrow']!r}")
    for b in c9["bars"]:
        want = b["full"] * (b["value"] - b["lo"]) / (b["hi"] - b["lo"])
        if abs(b["h"] - want) > 0.5 or not (b["lo"] <= b["value"] <= b["hi"]):
            fails.append(f"bar {b['key']}: height {b['h']:.1f} != {want:.1f}")
    fails += [f"banned text '{x}'" for x in (BANNED_V9 if banned is None else banned) if x in c9["text"]]
    return fails

METRICS = r"""() => {
  const lum = c => { const m = c.match(/[\d.]+/g).map(Number); const f = v => { v /= 255; return v <= 0.03928 ? v / 12.92 : Math.pow((v + 0.055) / 1.055, 2.4); };
    return [0.2126 * f(m[0]) + 0.7152 * f(m[1]) + 0.0722 * f(m[2]), m.length > 3 ? m[3] : 1]; };
  const bgOf = el => { for (let e = el; e && e.nodeType === 1; e = e.parentElement) { const b = getComputedStyle(e).backgroundColor;
    if (b && !/rgba\(0, 0, 0, 0\)|transparent/.test(b)) { const [l, a] = lum(b); if (a > 0.5) return l; } } return 1; };
  const texts = [], clipped = [];
  const stage = document.getElementById("stage");
  const walk = el => { for (const n of el.childNodes) {
    if (n.nodeType === 3 && n.textContent.trim()) {
      const p = n.parentElement; const rg = document.createRange(); rg.selectNodeContents(n);
      const rects = [...rg.getClientRects()].filter(r => r.width > 0.5);
      const cs = getComputedStyle(p); const lf = lum(cs.color)[0], lb = bgOf(p);
      const c = (Math.max(lf, lb) + 0.05) / (Math.min(lf, lb) + 0.05);
      rects.forEach(r => texts.push({ text: n.textContent.trim().slice(0, 50), size: parseFloat(cs.fontSize), contrast: +c.toFixed(2), x0: r.left, y0: r.top, x1: r.right, y1: r.bottom, id: texts.length, node: p.dataset.tid || (p.dataset.tid = Math.random().toString(36).slice(2)) }));
    } else if (n.nodeType === 1) walk(n); } };
  walk(stage);
  stage.querySelectorAll("*").forEach(e => { if (e.closest("svg") || !e.textContent.trim()) return;
    if (e.scrollWidth > e.clientWidth + 1 && getComputedStyle(e).display !== "inline" && e.clientWidth > 0) clipped.push(e.textContent.trim().slice(0, 50));
    const r = e.getBoundingClientRect(); if (r.right > innerWidth + 0.5 || r.bottom > innerHeight + 0.5 || r.left < -0.5 || r.top < -0.5) clipped.push("off-frame: " + e.textContent.trim().slice(0, 40)); });
  const vals = [...document.querySelectorAll("[data-key]")].map(e => ({ key: e.dataset.key, text: e.textContent.trim() }));
  return { texts, clipped, vals, bars: window.BARCOUNT || null, W: innerWidth, H: innerHeight };
}"""


def check(m):
    W, H, T, fails = m["W"], m["H"], m["texts"], []
    for t in T:
        e = min(t["x0"], t["y0"], W - t["x1"], H - t["y1"])
        if e < 63.5:
            fails.append(f"edge {e:.0f}px '{t['text']}'")
        if t["contrast"] < 7:
            fails.append(f"contrast {t['contrast']} '{t['text']}'")
        if t["size"] < 22:
            fails.append(f"size {t['size']}px '{t['text']}'")
    for i, a in enumerate(T):
        for b in T[i + 1:]:
            if a["node"] == b["node"]:
                continue
            ox = min(a["x1"], b["x1"]) - max(a["x0"], b["x0"]); oy = min(a["y1"], b["y1"]) - max(a["y0"], b["y0"])
            if ox > 1 and oy > 1:
                fails.append(f"overlap '{a['text']}' x '{b['text']}'")
    fails += [f"clipped '{c}'" for c in m["clipped"]]
    if m.get("bars") and m["bars"]["bars"] != m["bars"]["labels"]:   # pages that count bars: every bar carries its value
        fails.append(f"bars without a value label: {m['bars']['bars']} bars, {m['bars']['labels']} labels")
    if m.get("bars") and m["bars"].get("overlaps"):
        fails.append(f"{m['bars']['overlaps']} bar chart(s) whose last bar reaches the axis line")
    for v in m["vals"]:
        src = NS if v["key"].startswith("ns:") else NB
        k = v["key"][3:] if v["key"].startswith("ns:") else v["key"]
        want = src[k].get("shown", str(src[k]["value"]))
        if v["text"] != want:
            fails.append(f"value {v['key']}: '{v['text']}' != '{want}'")
    return {"fails": fails, "min_edge": round(min(min(t["x0"], t["y0"], W - t["x1"], H - t["y1"]) for t in T), 1),
            "min_contrast": min(t["contrast"] for t in T), "min_size": min(t["size"] for t in T),
            "values": {v["key"]: v["text"] for v in m["vals"]}}


def main():
    os.environ.setdefault("PLAYWRIGHT_BROWSERS_PATH", "/Volumes/afdev/venvs/video/browsers")
    from playwright.sync_api import sync_playwright
    which = sys.argv[1:] or list(JOBS)
    OUT.mkdir(parents=True, exist_ok=True)
    ck = HERE / "checks.json"
    res = json.loads(ck.read_text()) if ck.exists() else {}
    with sync_playwright() as pw:
        br = pw.chromium.launch(args=["--font-render-hinting=none"])
        for job in which:
            for page, layout, name in JOBS[job]:
                for W, H, suf in ((1920, 1080, ""), (1080, 1080, "_square")):
                    pg = br.new_page(viewport={"width": W, "height": H}, device_scale_factor=2)
                    errs = []
                    pg.on("pageerror", lambda e: errs.append(str(e)))
                    pg.goto((HERE / page).as_uri())
                    pg.evaluate("document.fonts.ready")
                    pg.evaluate("([W, H, l]) => build(W, H, l)", [W, H, layout])
                    png = OUT / f"{name}{suf}.png"
                    pg.screenshot(path=str(png), type="png")
                    if name.endswith(("_v3", "_v4", "_v5", "_v6", "_v7", "_v8", "_v9", "_v10")) or name in ("results_v4", "results_v5", "results_v6", "results_v7", "results_v8"):   # the removal test: the same render with every label hidden
                        pg.evaluate("notext()")
                        nt = OUT / f"{name}{suf}_notext.png"
                        pg.screenshot(path=str(nt), type="png")
                        Image.open(nt).resize((W, H), Image.LANCZOS).save(HERE / f"{name}{suf}_notext.png", optimize=True)
                        pg.evaluate("document.querySelectorAll('style').forEach(s => { if (s.textContent.includes('transparent !important')) s.remove(); })")
                    if name == "A1_flow" and not suf:   # the flow must read with every word hidden
                        pg.add_style_tag(content="#stage * { color: transparent !important; }")
                        pg.screenshot(path=str(OUT.parent / "images" / "architecture_notext.png"), type="png")
                        pg.evaluate("document.querySelectorAll('style').forEach(s => { if (s.textContent.includes('transparent !important')) s.remove(); })")
                    r = check(pg.evaluate(METRICS))
                    if name.endswith("_v8"):   # the v8 content rules
                        c8 = pg.evaluate(V8)
                        r["fails"] += c8["fails"] + [f"banned text '{b}'" for b in BANNED_V8 if b in c8["text"]]
                        if c8["overflow"]:
                            r["fails"].append(f"cards run {c8['overflow']:.0f}px into the footer")
                        if name.startswith("results") and c8["ncards"] < 4:
                            r["fails"].append(f"only {c8['ncards']} cards")
                    if name == "results_v9":   # the v9 rules
                        r["fails"] += check_v9(pg.evaluate(V9))
                    if name == "results_v10":   # the v9 rules with latency allowed, plus the v10 card set
                        panels = pg.evaluate("() => Object.fromEntries([...document.querySelectorAll('[data-panel]')].map(c => [c.dataset.panel, c.querySelectorAll('[data-metric]').length]))")
                        r["fails"] += check_v10(pg.evaluate(V9), panels)
                    if name == "architecture_v9":   # the head count and the turn-end box as drawn
                        t = pg.evaluate("() => document.getElementById('stage').innerText")
                        for need in ("Six small heads", "6 small heads", "classifier at each quiet frame", "v5, 2.5M, layer 8 + words", "turn head ≥ 0.99", "Turn head", "VAD head", "Is it you?", "Language?", "speaker head"):
                            if need not in t:
                                r["fails"].append(f"architecture_v9: missing '{need}'")
                    if errs:
                        r["fails"].insert(0, f"page errors {errs}")
                    im = Image.open(png)
                    r["size_px"] = list(im.size)
                    im.resize((W, H), Image.LANCZOS).save(HERE / f"{name}{suf}.png", optimize=True)
                    if name in FINAL:   # finals: full size to $DEMO_OUT/images, half size to demo/images (with the notext pair)
                        for fn in (f"{name}{suf}.png", f"{name}{suf}_notext.png"):
                            shutil.copyfile(OUT / fn, OUT.parent / "images" / fn)
                            shutil.copyfile(HERE / fn, HERE.parent / fn)
                    res[name + suf] = r
                    print(f"{name + suf:16s} {im.size} edge {r['min_edge']} contrast {r['min_contrast']} type {r['min_size']}px  FAIL: {r['fails'] or 'none'}")
                    pg.close()
        br.close()
    ck.write_text(json.dumps(res, indent=1))


if __name__ == "__main__":
    main()
