// Shared helpers for the B shots (chart_live.html, chart_wer.html, finale.html, end.html). Loaded after common.js and
// numbers_b.js (window.NB, generated by export_b.py from runs/*.json). Every frame is a pure function of t.
// Layout rule: the whole #content layer is pushed in to scale K by the end of the shot (chrome()), so everything is laid
// out inside B.box = the region that stays >= 64 px from every frame edge (and above the caption bar) at scale K.
// Palette: read from the builder's CSS variables in common.css (the values after the names are only fallbacks until
// common.css defines them): --bg, --ink, --muted (secondary type), --ours (audioforge), --pipecat, --livekit, --red
// (interruptions only). Flat: no gradients, glow or shadows.
const _css = (name, fb) => { const v = getComputedStyle(document.documentElement).getPropertyValue(name).trim(); return v || fb; };
const B = {
  NS: "http://www.w3.org/2000/svg",
  C: { bg: _css("--bg", "#0B0B0C"), ink: _css("--ink", "#FFFFFF"), muted: _css("--muted", "#A1A1A6"), ours: _css("--ours", "#FF7A1A"),
       pipecat: _css("--pipecat", "#8E8E93"), livekit: _css("--livekit", "#636366"), red: _css("--red", "#FF3B30") },
  GROW: 0.4, GD: 0.8,               // every bar and label grows on ONE clock: t in [GROW, GROW + GD]
  sv(tag, attrs, parent) { const e = document.createElementNS(B.NS, tag); for (const k in attrs) e.setAttribute(k, attrs[k]); if (parent) parent.appendChild(e); return e; },
  n(key) { const e = (window.NB || {})[key]; if (!e) throw new Error("numbers_b.js has no " + key); return e.value; },
  // the one string the film shows for a quantity (export_b.py rounds it once); a bar row built from a numbers_b key
  s(key) { const e = (window.NB || {})[key]; if (!e || e.shown == null) throw new Error("numbers_b.js has no shown value for " + key); return e.shown; },
  row(label, key, o = {}) { return Object.assign({ label, v: B.n(key), txt: B.s(key) }, o); },
  // d decimals, half away from zero, true minus sign
  f(v, d) { const s = (Math.sign(v) * Math.round(Math.abs(v) * Math.pow(10, d) + 1e-9) / Math.pow(10, d)).toFixed(d); return s.replace("-", "−"); },
  font() { return getComputedStyle(document.body).fontFamily; },
  tw(str, size, weight = 400) { const c = B._c || (B._c = document.createElement("canvas").getContext("2d")); c.font = `${weight} ${size}px ${B.font()}`; return c.measureText(str).width; },
  setup(W, H, fine, k = 1.03) {
    // a number never breaks from its unit in the fine print
    window.FINE = B.nb((window.PARAMS && window.PARAMS.fine) || fine || "");
    const ct = stage(W, H);
    B.fine = window.FINE; B.k = k; B.sq = S.sq;
    const ox = W * 0.5, oy = H * 0.45, M = S.M;
    const x0 = Math.ceil(ox - (ox - M) / k), x1 = Math.floor(ox + (W - M - ox) / k);
    const y0 = Math.ceil(oy - (oy - M) / k), y1 = Math.floor(oy + (S.bottom - oy) / k);
    B.box = { x0, x1, y0, y1, w: x1 - x0, h: y1 - y0 };
    B.hsize = S.sq ? 96 : 104;
    return ct;
  },
  frame(t, ctx) { chrome(t, Object.assign({}, ctx, { fine: ctx.fine || B.fine, push: B.k - 1 })); },
  abs(e, o) { e.style.position = "absolute"; return U.css(e, o); },
  // headline (wraps inside the box, never truncated) + optional sub line; returns the y below them
  // a number never breaks from its unit ("40 %", "1.2 s", "1.6×"): non-breaking space before the unit
  nb(str) { return String(str == null ? "" : str).replace(/(\d) (%|s|ms|×)(?=[\s,;.)·/]|$)/g, "$1\u00a0$2"); },
  header(ct, title, sub, y) {
    title = B.nb(title); sub = sub ? B.nb(sub) : sub;
    const bx = B.box; y = y == null ? bx.y0 + 10 : y;
    const h = B.abs(U.el("div", "h1", ct, title), { left: bx.x0, top: y, width: bx.w, fontSize: B.hsize });
    B.head = h; y += h.offsetHeight + 14;
    if (sub) { const s = B.abs(U.el("div", "sub", ct, sub), { left: bx.x0, top: y, width: bx.w, fontSize: 44, lineHeight: "1.2", color: B.C.muted }); B.subEl = s; y += s.offsetHeight + 10; }
    return y;
  },
  headerAnim(t) {
    const a0 = U.ease(U.seg(t, 0, 0.3));
    if (B.head) { B.head.style.opacity = a0; B.head.style.transform = `translateY(${(1 - a0) * 30}px)`; }
    if (B.subEl) B.subEl.style.opacity = U.ease(U.seg(t, 0.15, 0.3));
  },
  pill(ct, text, x, y, right) {
    text = B.nb(text);
    const p = B.abs(U.el("div", "pill", ct, text), { top: y, fontSize: 44, fontWeight: 700, color: B.C.bg, background: B.C.ours, padding: "10px 30px", borderRadius: "999px", whiteSpace: "nowrap", lineHeight: "1.2" });
    if (right) p.style.right = (S.W - x) + "px"; else p.style.left = x + "px";
    return p;
  },
  pillAnim(p, t, t0) { const a = U.ease(U.seg(t, t0, 0.3)); p.style.opacity = a; p.style.transform = `scale(${0.9 + 0.1 * a})`; },
  // ---- horizontal bar chart -------------------------------------------------------------------------------------
  // rows: {label, v, txt, ours, fill}: v sets the bar length, txt is the one string shown (numbers_b "shown").
  // spec: {max, unit, mode:"left"|"above", bh, vsize, t0}. Bars grow on one clock; each value label appears at its
  // final value only once its bar has landed (never a count-up).
  hbars(parent, x, y, w, h, spec, rows) {
    const svg = B.sv("svg", { width: w, height: h, viewBox: `0 0 ${w} ${h}`, overflow: "visible" });
    B.abs(svg, { left: x, top: y }); parent.appendChild(svg);
    const defs = B.sv("defs", {}, svg);
    const gid = "gl" + Math.random().toString(36).slice(2, 8);
    const vs = spec.vsize || 56, ls = spec.lsize || 44, n = rows.length, mode = spec.mode || "left", unit = spec.unit || "";
    const valText = r => B.nb(`${r.txt}${unit}`);
    const lw = mode === "left" ? Math.max(...rows.map(r => B.tw(r.label, ls, r.ours ? 700 : 400))) + 48 : 0;
    const vw = Math.max(...rows.map(r => B.tw(valText(r), vs, 700))) + 30;
    const bw = w - lw - vw;
    const rh = h / n, lab = mode === "above" ? ls * 1.25 : 0;
    const bh = Math.min(spec.bh || 96, (rh - lab) * (mode === "above" ? 0.6 : 0.62));
    const done = (spec.t0 != null ? spec.t0 : B.GROW) + B.GD;
    const out = [];
    rows.forEach((r, i) => {
      const g = B.sv("g", {}, svg);
      const yb = mode === "above" ? i * rh + lab + 6 : i * rh + (rh - bh) / 2;
      const col = r.ours ? B.C.ours : B.C.ink;
      const ly = mode === "left" ? yb + bh / 2 + ls * 0.35 : yb - 16;
      const label = B.sv("text", { x: 0, y: ly, "font-size": ls, "font-weight": r.ours ? 700 : 400, fill: col }, g); label.textContent = B.nb(r.label);
      const bar = B.sv("rect", { x: lw, y: yb, width: 0, height: bh, rx: 6, fill: r.fill || (r.ours ? B.C.ours : B.C.pipecat) }, g);
      const glint = null, clipR = null;
      const vt = B.sv("text", { x: lw + Math.max(bw * r.v / spec.max, 12) + 22, y: yb + bh / 2 + vs * 0.35, "font-size": vs, "font-weight": 700, fill: col }, g);
      vt.textContent = valText(r);
      vt.setAttribute("data-final", r.txt); vt.setAttribute("data-done", done);
      out.push({ r, g, bar, vt, glint, clipR, yb, label });
    });
    const o = { svg, rows: out, spec, lw, bw, bh, t0: done - B.GD };
    svg.setAttribute("data-primary", "");
    return o;
  },
  hbarsRender(o, t, t0 = o.t0) {
    const a = U.ease(U.seg(t, t0, B.GD)), sp = o.spec, done = t0 + B.GD;
    o.rows.forEach(({ r, g, bar, vt, glint, clipR }) => {
      const full = o.bw * r.v / sp.max, wd = full * a;
      const vis = Math.max(wd, a > 0 ? 12 * Math.min(1, a * 4) : 0);      // a small value still shows a sliver
      for (const e of [bar, clipR]) if (e) { e.setAttribute("x", o.lw); e.setAttribute("width", vis); e.setAttribute("rx", Math.min(6, vis / 2)); }
      vt.setAttribute("x", o.lw + Math.max(full, 12) + 22);
      vt.style.opacity = t >= done ? U.ease(U.seg(t, done, 0.12)).toFixed(3) : 0;   // final value only, once landed
      g.style.opacity = U.seg(t, t0 - 0.2, 0.25);
    });
    return a;
  },
  // legend chips: [[color, text, bold]]
  legend(ct, items, x, y, maxW) {
    const d = B.abs(U.el("div", "legend", ct), { left: x, top: y, width: maxW, display: "flex", flexWrap: "wrap", columnGap: "40px", rowGap: "8px", fontSize: 44, lineHeight: "1.2" });
    for (const [c, txt, bold] of items) {
      const s = U.el("span", null, d); U.css(s, { display: "inline-flex", alignItems: "center", gap: "16px", whiteSpace: "nowrap", color: bold ? B.C.ours : B.C.ink, fontWeight: bold ? 700 : 400 });
      const sw = U.el("i", null, s); U.css(sw, { display: "inline-block", width: 44, height: 28, borderRadius: 14, background: c });
      U.el("span", null, s, txt);
    }
    return d;
  },
};
window.B = B;
// flat near-black stage on every B page (no gradient, no light blob), whatever common.css still carries
{ const st = document.createElement("style");
  st.textContent = `#stage { background: ${B.C.bg} !important; } #light { display: none !important; } #fine { color: ${B.C.muted} !important; } .sub { color: ${B.C.muted}; }`;
  document.head.appendChild(st); }

// A chart page: headline, sub line, one or more panels of horizontal bars, fine print. Used by chart_icsi, chart_live,
// chart_turnbench and chart_wer. cfg: {title, sub, subSq, fine, fineSq, panels: () => [{title, rows, max, unit, note}],
// mode (16:9 row labels: "left" | "above")}. 16:9: panels side by side; 1:1: stacked. Every value comes from numbers_b.js.
function panelChart(cfg) {
  let P = [];
  window.init = function (data, params, W, H) {
    const sq = H / W > 0.9;
    const pick = (a, b) => (sq && b ? b : a)();
    const ct = B.setup(W, H, pick(cfg.fine, cfg.fineSq));
    const bx = B.box;
    let y = B.header(ct, typeof cfg.title === "function" ? cfg.title() : cfg.title, cfg.sub ? pick(cfg.sub, cfg.subSq) : null);
    // one-line takeaway in plain words, then a small setup line (what was compared)
    B.extra = [];
    if (cfg.takeaway) { const e = B.abs(U.el("div", "takeaway", ct, B.nb(cfg.takeaway())), { left: bx.x0, top: y, width: bx.w, fontSize: sq ? 44 : 48, lineHeight: "1.2", color: B.C.ink }); B.extra.push(e); y += e.offsetHeight + 8; }
    if (cfg.setup) { const e = B.abs(U.el("div", "setup", ct, B.nb(cfg.setup())), { left: bx.x0, top: y, width: bx.w, fontSize: 36, lineHeight: "1.2", color: B.C.muted }); B.extra.push(e); y += e.offsetHeight; }
    y += sq ? 16 : 28;
    const panels = cfg.panels(params || {});
    const np = panels.length, side = np > 1 && !sq, gap = side ? 72 : 28;
    const h = bx.y1 - y;
    const prim = B.abs(U.el("div", null, ct), { left: bx.x0, top: y, width: bx.w, height: h, pointerEvents: "none" }); prim.setAttribute("data-primary", "");
    const weights = panels.map(p => p.weight || p.rows.length + (p.title ? 0.9 : 0));
    const wsum = weights.reduce((a, b) => a + b, 0);
    let yy = y;
    panels.forEach((p, i) => {
      const pw = side ? (bx.w - gap * (np - 1)) / np : bx.w;
      const ph = side ? h : (h - gap * (np - 1)) * weights[i] / wsum;
      const px = side ? bx.x0 + i * (pw + gap) : bx.x0, py = side ? y : yy;
      yy += ph + gap;
      let top = py;
      let tEl = null, nEl = null;
      if (p.title) {
        tEl = B.abs(U.el("div", "ptitle", ct, B.nb(p.title)), { left: px, top, width: pw, fontSize: 44, fontWeight: 700, lineHeight: "1.2", color: B.C.ink });
        top += tEl.offsetHeight + (sq ? 6 : 14);
      }
      const mode = p.mode || cfg.mode || "left";
      const noteH = p.note ? 88 : 0;
      const pmax = p.max != null ? p.max : Math.max(...p.rows.map(r => r.v)) * 1.02;    // zero baseline; the longest bar fills the panel
      const o = B.hbars(ct, px, top, pw, py + ph - top - noteH, { max: pmax, unit: p.unit, mode, bh: p.bh || (sq ? 48 : 56), vsize: p.vsize || (sq ? 52 : 56), lsize: p.lsize }, p.rows);
      o.svg.removeAttribute("data-primary");
      if (p.note) nEl = B.pill(ct, p.note, px, py + ph - noteH + 12);
      P.push({ o, tEl, nEl });
    });
  };
  window.render = function (t, ctx) {
    B.frame(t, ctx); B.headerAnim(t);
    (B.extra || []).forEach(e => { e.style.opacity = U.ease(U.seg(t, 0.15, 0.3)); });
    for (const p of P) {
      B.hbarsRender(p.o, t);
      if (p.tEl) p.tEl.style.opacity = U.ease(U.seg(t, 0.2, 0.3));
      if (p.nEl) B.pillAnim(p.nEl, t, B.GROW + B.GD + 0.35);
    }
  };
}
window.panelChart = panelChart;
